server:
  port: 9000

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shoppingcart  #port numbers may vary for all, please write your own port
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  hateoas:
    use-hal-as-default-json-media-type: false